### ISSUE TITLE
typo: As a customer*  ...

### ISSUE THREAD

**Issue by jamilxt** [Apurba000/ecommerce-spring#30]
https://github.com/Apurba000/ecommerce-spring/blob/7ea354c1c42c8fd51c3755b083ad87ab33fcce52/README.md?plain=1#L5C11-L5C15

**Comment by Apurba000** [comment]
Resolved at : https://github.com/Apurba000/ecommerce-spring/commit/2c746aab584307b9103c4e256e88c2c03e8b9ac0
